# ================================
# AI REPORT (COMPATIBILE AGENTE PRO)
# ================================

import pandas as pd

# ================================
# UTILS
# ================================

def safe_format(value, digits=2, suffix=""):
    if value is None:
        return "N/A"
    try:
        return f"{round(float(value), digits)}{suffix}"
    except:
        return "N/A"

def get_last(series):
    try:
        s = series.dropna()
        if len(s) == 0:
            return None, None
        return s.iloc[-1], s.index[-1].strftime("%Y-%m-%d")
    except:
        return None, None

# ================================
# MAIN REPORT
# ================================

def generate_ai_report(fred_data, score, level, headlines, sentiment):

    report = ""
    report += "🧠 AI BUBBLE REPORT\n"
    report += "=========================\n\n"

    # ================================
    # MACRO DATA
    # ================================

    report += "📊 MACRO CONDITIONS\n"

    prod_val, prod_date = get_last(fred_data.get('productivity', pd.Series()))
    labor_val, labor_date = get_last(fred_data.get('unit_labor_cost', pd.Series()))
    sent_val, sent_date = get_last(fred_data.get('consumer_sentiment', pd.Series()))
    vix_val, vix_date = get_last(fred_data.get('vix', pd.Series()))
    spread_val, spread_date = get_last(fred_data.get('high_yield_spread', pd.Series()))

    report += f"- Productivity: {safe_format(prod_val,2,'%')} ({prod_date})\n"
    report += f"- Unit Labor Cost: {safe_format(labor_val,2,'%')} ({labor_date})\n"
    report += f"- Consumer Sentiment: {safe_format(sent_val,1)} ({sent_date})\n"
    report += f"- VIX: {safe_format(vix_val,1)} ({vix_date})\n"
    report += f"- Credit Spread: {safe_format(spread_val,2)} ({spread_date})\n"

    # ================================
    # RISK SUMMARY
    # ================================

    report += "\n⚠️ RISK ANALYSIS\n"
    report += f"- Bubble Score: {score}\n"
    report += f"- Risk Level: {level}\n"

    if score >= 5:
        report += "- Interpretation: Elevated systemic stress detected\n"
    elif score >= 3:
        report += "- Interpretation: Moderate risk environment\n"
    else:
        report += "- Interpretation: Stable macro backdrop\n"

    # ================================
    # NEWS ANALYSIS
    # ================================

    report += "\n📰 NEWS & SENTIMENT\n"
    report += f"- Sentiment Score: {safe_format(sentiment,2)}\n"
    report += f"- Headlines Analyzed: {len(headlines)}\n"

    if sentiment > 0.5:
        report += "- Tone: Positive / optimistic narrative\n"
    elif sentiment < -0.5:
        report += "- Tone: Negative / risk-off narrative\n"
    else:
        report += "- Tone: Neutral / mixed narrative\n"

    report += "\nTop Headlines:\n"

    for h in headlines[:5]:
        report += f"• {h}\n"

    # ================================
    # SYNTHESIS
    # ================================

    report += "\n🧠 SYNTHESIS\n"

    if sentiment > 0.5 and score >= 4:
        report += "Potential disconnect: strong narrative + fragile macro → bubble risk building\n"

    elif sentiment > 0.5 and score < 3:
        report += "Positive narrative supported by stable macro conditions\n"

    elif sentiment < 0 and score >= 4:
        report += "Negative sentiment aligned with macro deterioration\n"

    else:
        report += "No extreme divergence between narrative and fundamentals\n"

    report += "\n=========================\n"
    report += "Generated by AI Bubble Agent PRO\n"

    return report